### ISSUE TITLE
RTree creation API might seem a bit contraintuitive

### ISSUE THREAD

**Issue by pereferrera** [davidmoten/rtree#20]
Hello,
First of all thanks for this library, it is very useful and overall well done. I just got stuck with it for some minutes, not realizing what was wrong in my code. I finally realized that the RTree object is returning a new copy of itself when adding a point. This makes sense with the concept of immutable RTree, and I recognize I should have paid more attention when reading the examples. However I think this API is contraintuitive - If the RTree is immutable then why does it have an add() method? - and might lead to the same mistake by other people. What I would suggest as an improved API is to make an RTreeBuilder, which would be in charge of receiving all the points and then create an immutable RTree, which wouldn't have the method add(). If online modifications to the RTree are needed maybe they can be provided via static methods of it, e.g. RTreeBuilder.delete(tree, point): RTree

**Comment by davidmoten** [comment]
Thanks for your input and I'm glad you are finding the library useful.

So the static method approach means you can't use method chaining so code like:

```java
tree = RTree.create()
                   .add(1, point(2,3))
                   .add(2, point(5,2))
                   .add(3, point(9,4));
```

becomes much more verbose and less discoverable to make happen with static add methods:

```java
tree = RTreeBuilder.add(RTreeBuilder.create(), 1, point(2,3));
tree = RTreeBuilder.add(tree, 2, point(5,2));
tree = RTreeBuilder.add(tree, 3, point(9,4));
```

For an immutable data structure I would never expect add to do anything but return a new object otherwise it's not immutable and you make that point too. ```add``` in this case means create a new RTree based on the current tree with the item added to it. Perhaps a better name for the method or I could emphasise what add is doing in the documentation in the README. I don't like the idea of using a builder because it just makes for unnecessary typing and I'm not keen to lose method chaining.

**Comment by pereferrera** [comment]
Actually I thought about a normal builder, so you could chain and use it with build() in the end like .add().add().build(). But then I realized that you often want to perform online modifications so a builder is not really suited for that... And the static method for that purpose might be also not so nice, I agree.

Just emphasizing what the immutable operations do in the README would probably be fine then.

**Comment by davidmoten** [comment]
Righto, I'll update the README. Thanks for your input.
