### ISSUE TITLE
implement java.io.Serializable

### ISSUE THREAD

**Issue by AhmedObaidi** [davidmoten/rtree#24]
It would be great if RTree could be serialized to io.

**Comment by davidmoten** [comment]
I'm a bit reluctant to implement Serializable because the Serialized form becomes part of the API and in theory should be supported as the API changes. Can you convince me?

**Comment by AhmedObaidi** [comment]
I'm testing some code for RTree as in-memory cache for large number of spatial objects and do the search on that. My biggest concern is not to hit the database for full re-load every time the server is restarted. Instead, I would rather serialize the tree to disk and only load the delta from the database.

**Comment by davidmoten** [comment]
I'm not keen to Serialize the RTree class but might be able to meet halfway and make Entry and the standard geometry types Serializable. That way rebuilding the RTree from a sequence of Entry objects taken from an ObjectInputStream would be quite trivial. I'll have a closer look at those classes to see if there are hiccups. I see one hiccup in Circle because the class has a final reference to the minimum bounding rectangle as an optimization. Being a derived field I wouldn't normally expect it to be serialized then deserializing bypasses the constructor so it wouldn't be initialized.

**Comment by AhmedObaidi** [comment]
I don't know, it might make more sense for me to serialize my objects in a ArrayList and create the Entry and the tree from there. 

By the way,  many thanks for the RTree, great implementation.

**Comment by davidmoten** [comment]
That sounds good to me.

**Comment by davidmoten** [comment]
By the way here are utilities for serialization and deserialization using RxJava:

https://github.com/davidmoten/rxjava-extras/blob/master/README.md#serialized

**Comment by davidmoten** [comment]
RTree serialization now supported by 0.8-RC1 using flatbuffers (fast reading and writing and low-memory usage if desired).
