### ISSUE TITLE
Bulk loading (with STR)

### ISSUE THREAD

**Issue by x2b** [davidmoten/rtree#45]
I have a rather large set of entries (>= 300k) and I would like to somewhat improve the performance of the tree. The data is available beforehand so I think that bulk loading might help, in particular the "Sort-Tile-Recursive" strategy. I think this could be implemented fairly easily.

**Comment by davidmoten** [comment]
Thanks I'll have a look. If the data is static you can use serialisation by
the way. Look at README.md.

**Comment by ambling** [comment]
hi @davidmoten 

Can you review my implementation of this feature?

**Comment by david-bouyssie** [comment]
Do you observe a speed improvement relative to the R*Tree creation?
I also need to handle very large datasets and the R*Tree creation time is my biggest issue.

Thanks!

**Comment by ambling** [comment]
Hi, actually I am still working on the performance evaluation. Sorry for the delay.

I have tried to add more test cases in this benchmark class in [this branch](https://github.com/ambling/rtree/tree/comprehensive_benchmarking), however it seems to mess up the codebase and it is very tedious to make some changes to the rtree types or datasets. 

So I opened a [new project](https://github.com/ambling/rtree-benchmark) according to the guide of [jmh](http://openjdk.java.net/projects/code-tools/jmh/), and trying to make the code more clean with help of the [inheritance feature](http://hg.openjdk.java.net/code-tools/jmh/file/704bfc869f77/jmh-samples/src/main/java/org/openjdk/jmh/samples/JMHSample_24_Inheritance.java).

I am no familiar with jmh, so I would greatly appreciate if you guys have any suggestions on this benchmark project.

BTW, maybe this issue is safe to close and leave me some more days to open a new PR to update the README docs after I have mature benchmarking results?

**Comment by davidmoten** [comment]
ok closing, thanks for your efforts @ambling

**Comment by david-bouyssie** [comment]
@ambling: Thank you for setting up this benchmarking project.
I'll try to have a look at it.
