### ISSUE TITLE
Would you plan to provide a method that deletes entries according to a value?

### ISSUE THREAD

**Issue by JamesChenX** [davidmoten/rtree#94]
I really love the cool rtree dependency, but what gives me a headache is the method "delete" which cannot be invoked when provided with only the value of the Entry.
What the dependency provides is:
`public RTree<T, S> delete(T value, S geometry)`
But what I want is(Delete entries according to its value):
`public RTree<T, S> delete(T value)`
Of course, I can save both the value and the geometry of entries before adding an entry into it, and deleting them according to what I have. But it's really redundant and I don't think it should be a graceful implementation.

So, would you have any plan to add this feature?
Thanks.

**Comment by davidmoten** [comment]
if it was `public RTree<T, S> delete(T value)` then the whole RTree would need to be scanned for that value. Fast performance on such a use case is not what an RTree is targeted for and adding support for it would probably be to maintain a Multimap in addition to the RTree. This is of course wasteful in terms of memory so I don't think we should do it.

The short answer is that you save the geometry yourself before adding to it (you manage your own Multimap).  Note that I refer to a Mutlimap because one value may have many entries in the RTree.

**Comment by JamesChenX** [comment]
I understand now. Thank you for your detailed response.
